export const CREATE_PROFILE_INFO = 'CREATE_PROFILE_INFO'
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO'
export const EDIT_PROFILE_INFO = 'EDIT_PROFILE_INFO'
export const DELETE_PROFILE_INFO = 'DELETE_PROFILE_INFO'

export const CREATE_CONTACT_INFO = 'CREATE_CONTACT_INFO'
export const GET_CONTACT_INFO = 'GET_CONTACT_INFO'
export const EDIT_CONTACT_INFO = 'EDIT_CONTACT_INFO'
export const DELETE_CONTACT_INFO = 'DELETE_CONTACT_INFO'

export const CREATE_POSTJOB = 'CREATE_POSTJOB'
export const GET_POSTJOB = 'GET_POSTJOB'
export const EDIT_POSTJOB = 'EDIT_POSTJOB'
export const DELETE_POSTJOB = 'DELETE_POSTJOB'