export const CREATE_PROFILE_INFO = 'CREATE_PROFILE_INFO'
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO'
export const EDIT_PROFILE_INFO = 'EDIT_PROFILE_INFO'
export const DELETE_PROFILE_INFO = 'DELETE_PROFILE_INFO'
export const CLEAR_PROFILE_INFO = 'CLEAR_PROFILE_INFO'

export const CREATE_CONTACT_INFO = 'CREATE_CONTACT_INFO'
export const GET_CONTACT_INFO = 'GET_CONTACT_INFO'
export const EDIT_CONTACT_INFO = 'EDIT_CONTACT_INFO'
export const DELETE_CONTACT_INFO = 'DELETE_CONTACT_INFO'

export const CREATE_POSTJOB = 'CREATE_POSTJOB'
export const GET_POSTJOB = 'GET_POSTJOB'
export const EDIT_POSTJOB = 'EDIT_POSTJOB'
export const DELETE_POSTJOB = 'DELETE_POSTJOB'

export const CREATE_EDUCATION = 'CREATE_EDUCATION'
export const GET_EDUCATION = 'GET_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'
export const DELETE_EDUCATION = 'DELETE_EDUCATION'
export const GET_EDUCATIONS = 'GET_EDUCATIONS'

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE'
export const GET_EXPERIENCE = 'GET_EXPERIENCE'
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE'
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE'
export const GET_EEXPERIENCES = 'GET_EEXPERIENCES'


export const CREATE_KEYSKILLS = 'CREATE_KEYSKILLS'
export const GET_KEYSKILLS = 'GET_KEYSKILLS'
export const EDIT_KEYSKILLS = 'EDIT_KEYSKILLS'
export const DELETE_KEYSKILLS = 'DELETE_KEYSKILLS'

export const CREATE_TECH_SKILLS = 'CREATE_TECH_SKILLS'
export const GET_TECH_SKILLS = 'GET_TECH_SKILLS'
export const GET_SELECTED_TECH_SKILLS = 'GET_SELECTED_TECH_SKILLS'
export const EDIT_TECH_SKILLS = 'EDIT_TECH_SKILLS'
export const DELETE_TECH_SKILLS = 'DELETE_TECH_SKILLS'

export const CREATE_ACHIEVEMENTS = 'CREATE_ACHIEVEMENTS'
export const GET_ACHIEVEMENTS = 'GET_ACHIEVEMENTS'
export const EDIT_ACHIEVEMENTS = 'EDIT_ACHIEVEMENTS'
export const DELETE_ACHIEVEMENTS = 'DELETE_ACHIEVEMENTS'


export const SAVE_LANGUAGES = 'SAVE_LANGUAGES'
export const GET_LANGUAGES = 'GET_LANGUAGES'
export const GET_LANGUAGES_UZ = 'GET_LANGUAGES_UZ'
export const GET_LANGUAGES_RU = 'GET_LANGUAGES_RU'
export const GET_LANGUAGES_EN = 'GET_LANGUAGES_EN'

export const CREATE_DRIVING_L = 'CREATE_DRIVING_L'
export const GET_DRIVING_L = 'GET_DRIVING_L'
export const EDIT_DRIVING_L = 'EDIT_DRIVING_L'
export const DELETE_DRIVING_L = 'DELETE_DRIVING_L'

export const CREATE_PERSONAL_DEV = 'CREATE_PERSONAL_DEV'
export const GET_PERSONAL_DEV= 'GET_PERSONAL_DEV'
export const EDIT_PERSONAL_DEV = 'EDIT_PERSONAL_DEV'
export const DELETE_PERSONAL_DEV = 'DELETE_PERSONAL_DEV'

export const CREATE_COLOR = 'CREATE_COLOR'
export const SELECT_COLOR = 'SELECT_COLOR'


export const GET_NUMBERS_1_100 = 'GET_NUMBERS_1_100'


export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const CREATE_OBEKTIVKA = 'CREATE_OBEKTIVKA'
export const GET_OBEKTIVKA= 'GET_OBEKTIVKA'
export const EDIT_OBEKTIVKA = 'EDIT_OBEKTIVKA'
export const DELETE_OBEKTIVKA = 'DELETE_OBEKTIVKA'

export const CREATE_OBEKTIVKA_PROFILE = 'CREATE_OBEKTIVKA_PROFILE'
export const GET_OBEKTIVKA_PROFILE= 'GET_OBEKTIVKA_PROFILE'
export const EDIT_OBEKTIVKA_PROFILE = 'EDIT_OBEKTIVKA_PROFILE'
export const DELETE_OBEKTIVKA_PROFILE = 'DELETE_OBEKTIVKA_PROFILE'

export const CREATE_OBEKTIVKA_BIRTH = 'CREATE_OBEKTIVKA_BIRTH'
export const GET_OBEKTIVKA_BIRTH= 'GET_OBEKTIVKA_BIRTH'
export const EDIT_OBEKTIVKA_BIRTH = 'EDIT_OBEKTIVKA_BIRTH'
export const DELETE_OBEKTIVKA_BIRTH = 'DELETE_OBEKTIVKA_BIRTH'

export const CREATE_OBEKTIVKA_ACADEMIC = 'CREATE_OBEKTIVKA_ACADEMIC'
export const GET_OBEKTIVKA_ACADEMIC= 'GET_OBEKTIVKA_ACADEMIC'
export const EDIT_OBEKTIVKA_ACADEMIC = 'EDIT_OBEKTIVKA_ACADEMIC'
export const DELETE_OBEKTIVKA_ACADEMIC = 'DELETE_OBEKTIVKA_ACADEMIC'

export const CREATE_OBEKTIVKA_AWARDS = 'CREATE_OBEKTIVKA_AWARDS'
export const GET_OBEKTIVKA_AWARDS= 'GET_OBEKTIVKA_AWARDS'
export const EDIT_OBEKTIVKA_AWARDS = 'EDIT_OBEKTIVKA_AWARDS'
export const DELETE_OBEKTIVKA_AWARDS = 'DELETE_OBEKTIVKA_AWARDS'

export const CREATE_OBEKTIVKA_MP = 'CREATE_OBEKTIVKA_MP'
export const GET_OBEKTIVKA_MP= 'GET_OBEKTIVKA_MP'
export const EDIT_OBEKTIVKA_MP = 'EDIT_OBEKTIVKA_MP'
export const DELETE_OBEKTIVKA_MP = 'DELETE_OBEKTIVKA_MP'

export const CREATE_OBEKTIVKA_EXPERIENCE = 'CREATE_OBEKTIVKA_EXPERIENCE'
export const GET_OBEKTIVKA_EXPERIENCE= 'GET_OBEKTIVKA_EXPERIENCE'
export const EDIT_OBEKTIVKA_EXPERIENCE = 'EDIT_OBEKTIVKA_EXPERIENCE'
export const DELETE_OBEKTIVKA_EXPERIENCE = 'DELETE_OBEKTIVKA_EXPERIENCE'

export const CREATE_OBEKTIVKA_LANGUAGES = 'CREATE_OBEKTIVKA_LANGUAGES'
export const GET_OBEKTIVKA_LANGUAGES= 'GET_OBEKTIVKA_LANGUAGES'
export const EDIT_OBEKTIVKA_LANGUAGES = 'EDIT_OBEKTIVKA_LANGUAGES'
export const DELETE_OBEKTIVKA_LANGUAGES = 'DELETE_OBEKTIVKA_LANGUAGES'

export const CREATE_OBEKTIVKA_RELATIVES = 'CREATE_OBEKTIVKA_RELATIVES'
export const GET_OBEKTIVKA_RELATIVES= 'GET_OBEKTIVKA_RELATIVES'
export const EDIT_OBEKTIVKA_RELATIVES = 'EDIT_OBEKTIVKA_RELATIVES'
export const DELETE_OBEKTIVKA_RELATIVES = 'DELETE_OBEKTIVKA_RELATIVES'

export const CREATE_SEARCH_FORM = 'CREATE_SEARCH_FORM'
export const GET_SEARCH_FORM= 'GET_SEARCH_FORM'
