export const CREATE_PROFILE_INFO = 'CREATE_PROFILE_INFO'
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO'
export const EDIT_PROFILE_INFO = 'EDIT_PROFILE_INFO'
export const DELETE_PROFILE_INFO = 'DELETE_PROFILE_INFO'

export const CREATE_CONTACT_INFO = 'CREATE_CONTACT_INFO'
export const GET_CONTACT_INFO = 'GET_CONTACT_INFO'
export const EDIT_CONTACT_INFO = 'EDIT_CONTACT_INFO'
export const DELETE_CONTACT_INFO = 'DELETE_CONTACT_INFO'

export const CREATE_POSTJOB = 'CREATE_POSTJOB'
export const GET_POSTJOB = 'GET_POSTJOB'
export const EDIT_POSTJOB = 'EDIT_POSTJOB'
export const DELETE_POSTJOB = 'DELETE_POSTJOB'

export const CREATE_EDUCATION = 'CREATE_EDUCATION'
export const GET_EDUCATION = 'GET_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'
export const DELETE_EDUCATION = 'DELETE_EDUCATION'
export const GET_EDUCATIONS = 'GET_EDUCATIONS'

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE'
export const GET_EXPERIENCE = 'GET_EXPERIENCE'
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE'
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE'
export const GET_EEXPERIENCES = 'GET_EEXPERIENCES'


export const CREATE_KEYSKILLS = 'CREATE_KEYSKILLS'
export const GET_KEYSKILLS = 'GET_KEYSKILLS'
export const EDIT_KEYSKILLS = 'EDIT_KEYSKILLS'
export const DELETE_KEYSKILLS = 'DELETE_KEYSKILLS'



